### ISSUE TITLE
Compilation error due to missing include of `"tuple"`

### ISSUE THREAD

**Issue by jjerphan** [IntelPython/dpctl#1007]
First, thank you for developping dpctl!

Following @oleksandr-pavlyk's instructions https://github.com/oleksandr-pavlyk/kmeans_dpcpp/issues/1#issuecomment-1334236131, when lauching the compilation of `dpctl` with:

```bash
python scripts/build_locally.py
```

I have the following compilation error:

```
[103/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o
FAILED: dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o 
/opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx -D_tensor_impl_EXPORTS -I/home/jjerphan/dev/dpctl/dpctl/tensor/../include -I/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/include -I/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source -isystem /home/jjerphan/.local/share/miniconda3/envs/intel/include/python3.9 -isystem /home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-build/_deps/pybind11-src/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jjerphan/.local/share/miniconda3/envs/intel/include -fsycl  -O3 -Wall -Wextra -Winit-self -Wunused-function -Wuninitialized -Wmissing-declarations -fdiagnostics-color=auto -fstack-protector -fstack-protector-all -fpic -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fno-strict-overflow -fno-delete-null-pointer-checks -fsycl  -O3 -DNDEBUG -fPIC -fvisibility=hidden -ipo -std=c++17 -MD -MT dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o -MF dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o.d -o dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o -c /home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source/simplify_iteration_space.cpp
In file included from /home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source/simplify_iteration_space.cpp:25:
In file included from /home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source/simplify_iteration_space.hpp:26:
/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/include/utils/strided_iters.hpp:517:17: error: no member named 'make_tuple' in namespace 'std'
    return std::make_tuple(out_shape, out_strides, disp);
           ~~~~~^
/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/include/utils/strided_iters.hpp:540:17: error: no member named 'make_tuple' in namespace 'std'
    return std::make_tuple(out_shape, out_strides1, disp1, out_strides2, disp2);
           ~~~~~^
2 errors generated.
```

After inspection, modification and retrial, I think this error is due to a missing include directive for `tuple` in `dpctl/tensor/libtensor/include/utils/strided_iters.hpp`.

---

<details>
<summary>Full Trace</summary>

```
/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(


--------------------------------------------------------------------------------
-- Trying "Ninja" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is IntelLLVM 2022.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is IntelLLVM 2022.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jjerphan/dev/dpctl/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja" generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-build
  Command:
    cmake /home/jjerphan/dev/dpctl -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/include/python3.9 -DPYTHON_LIBRARY:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/python -DPython_ROOT_DIR:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel -DPython_INCLUDE_DIR:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/include/python3.9 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/python -DPython3_ROOT_DIR:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel -DPython3_INCLUDE_DIR:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/include/python3.9 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/numpy/core/include -DCMAKE_AR=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-strip -DCMAKE_C_COMPILER:PATH=icx -DCMAKE_CXX_COMPILER:PATH=icpx -DDPCTL_ENABLE_L0_PROGRAM_CREATION=ON -DDPCTL_ENABLE_GLOG:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_AR=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/home/jjerphan/.local/share/miniconda3/envs/intel/bin/x86_64-conda-linux-gnu-strip

-- The CXX compiler identification is IntelLLVM 2022.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Echo from /home/jjerphan/dev/dpctl/IntelDPCPPConfig.cmake
-- The SYCL compiler is /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx
-- The SYCL Flags are -fsycl 
-- The SYCL Language Version is 202001
-- Found IntelDPCPP: /opt/intel/oneapi/compiler/2022.2.1/linux/include (found version "202001") 
-- The C compiler identification is IntelLLVM 2022.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "2.38.1") 
-- Echo from /home/jjerphan/dev/dpctl/libsyclinterface/IntelDPCPPConfig.cmake
-- The SYCL compiler is /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx
-- The SYCL Flags are -fsycl 
-- The SYCL Language Version is 202001
-- Echo from /home/jjerphan/dev/dpctl/libsyclinterface/IntelDPCPPConfig.cmake
-- The SYCL compiler is /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx
-- The SYCL Flags are -fsycl 
-- The SYCL Language Version is 202001
-- dpcpp ver[0]: Intel(R) oneAPI DPC++/C++ Compiler 2022.2.1 (2022.2.1.20221020)
-- dpcpp ver[1]: Target: x86_64-unknown-linux-gnu
-- dpcpp ver[2]: Thread model: posix
-- dpcpp ver[3]: InstalledDir: /opt/intel/oneapi/compiler/2022.2.1/linux/bin-llvm
-- dpcpp ver[4]: Configuration file: /opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx.cfg
-- Found IntelSycl: TRUE  
-- Level zero headers downloaded to: /home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-build/level-zero/include
-- LIB_ZE: libze_loader.so.1
-- LIB_CL: libOpenCL.so.1
CMake Warning (dev) at /home/jjerphan/.local/share/miniconda3/envs/intel/share/cmake-3.25/Modules/FetchContent.cmake:1279 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  CMakeLists.txt:34 (FetchContent_Declare)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- pybind11 v2.10.1 
-- Found PythonInterp: /home/jjerphan/.local/share/miniconda3/envs/intel/bin/python (found suitable version "3.9.15", minimum required is "3.6") 
-- Found PythonLibs: /home/jjerphan/.local/share/miniconda3/envs/intel/lib/libpython3.9.so
-- Performing Test HAS_INTEL_IPO
-- Performing Test HAS_INTEL_IPO - Success
-- Found PythonInterp: /home/jjerphan/.local/share/miniconda3/envs/intel/bin/python (found version "3.9.15") 
-- Found PythonLibs: /home/jjerphan/.local/share/miniconda3/envs/intel/lib/libpython3.9.so (found version "3.9.15") 
-- Found NumPy: /usr/include (found version "1.23.5") 
-- Found Cython: /home/jjerphan/.local/share/miniconda3/envs/intel/bin/cython  
-- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
_modinit_prefix:PyInit_
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    Python3_EXECUTABLE
    Python3_FIND_REGISTRY
    Python3_INCLUDE_DIR
    Python3_NumPy_INCLUDE_DIRS
    Python3_ROOT_DIR
    Python_FIND_REGISTRY
    Python_INCLUDE_DIR
    Python_NumPy_INCLUDE_DIRS
    Python_ROOT_DIR


-- Build files have been written to: /home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-build
[1/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_device_selection.cpp.o
[2/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_platform_interface.cpp.o
[3/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_service.cpp.o
[4/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_event_interface.cpp.o
[5/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_device_selector_interface.cpp.o
[6/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_device_manager.cpp.o
[7/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_utils.cpp.o
[8/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_device_interface.cpp.o
[9/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_context_interface.cpp.o
[10/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_kernel_interface.cpp.o
[11/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_kernel_bundle_interface.cpp.o
[12/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_queue_manager.cpp.o
[13/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_usm_interface.cpp.o
[14/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_platform_manager.cpp.o
[15/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/helper/source/dpctl_utils_helper.cpp.o
[16/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/helper/source/dpctl_error_handlers.cpp.o
[17/114] Building CXX object libsyclinterface/CMakeFiles/DPCTLSyclInterface.dir/source/dpctl_sycl_queue_interface.cpp.o
[18/114] Linking CXX shared library libsyclinterface/libDPCTLSyclInterface.so.0.14
[19/114] Creating library symlink libsyclinterface/libDPCTLSyclInterface.so.0 libsyclinterface/libDPCTLSyclInterface.so
[20/114] cd /home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-build/dpctl && /home/jjerphan/.local/share/miniconda3/envs/intel/bin/cmake -E make_directory /home/jjerphan/dev/dpctl/dpctl/include && /home/jjerphan/.local/share/miniconda3/envs/intel/bin/cmake -E make_directory /home/jjerphan/dev/dpctl/dpctl/include/syclinterface && /home/jjerphan/.local/share/miniconda3/envs/intel/bin/cmake -E make_directory /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/Support && /home/jjerphan/.local/share/miniconda3/envs/intel/bin/cmake -E make_directory /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/Config
[21/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/dpctl4pybind11.hpp
[22/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/dpctl_capi.h
[23/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/dpctl_sycl_interface.h
[24/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/Config/dpctl_config.h
[25/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/Support/DllExport.h
[26/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/Support/MemOwnershipAttrs.h
[27/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/Support/ExternC.h
[28/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_data_types.h
[29/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_service.h
[30/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_context_interface.h
[31/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_device_manager.h
[32/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_device_selector_interface.h
[33/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_error_handler_type.h
[34/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_device_interface.h
[35/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_enum_types.h
[36/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_event_interface.h
[37/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_kernel_bundle_interface.h
[38/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_kernel_interface.h
[39/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_platform_interface.h
[40/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_queue_interface.h
[41/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_queue_manager.h
[42/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_platform_manager.h
[43/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_types.h
[44/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_vector.h
[45/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_sycl_usm_interface.h
[46/114] Generating /home/jjerphan/dev/dpctl/dpctl/include/syclinterface/dpctl_utils.h
[47/114] Generating CXX source dpctl/_diagnostics.cxx
[48/114] Generating CXX source dpctl/_sycl_platform.cxx
[49/114] Generating CXX source dpctl/_sycl_device_factory.cxx
[50/114] Generating CXX source dpctl/_sycl_event.cxx
[51/114] Generating CXX source dpctl/_sycl_device.cxx
[52/114] Generating CXX source dpctl/_sycl_queue_manager.cxx
[53/114] Generating CXX source dpctl/program/_program.cxx
[54/114] Generating CXX source dpctl/_sycl_queue.cxx
[55/114] Generating CXX source dpctl/_sycl_context.cxx
[56/114] Generating CXX source dpctl/memory/_memory.cxx
[57/114] Building CXX object dpctl/CMakeFiles/_diagnostics.dir/_diagnostics.cxx.o
[58/114] Linking CXX shared module dpctl/_diagnostics.cpython-39-x86_64-linux-gnu.so
[59/114] Copying Cython-generated headers to dpctl
[60/114] Building CXX object dpctl/CMakeFiles/_sycl_device_factory.dir/_sycl_device_factory.cxx.o
[61/114] Building CXX object dpctl/CMakeFiles/_sycl_platform.dir/_sycl_platform.cxx.o
[62/114] Linking CXX shared module dpctl/_sycl_device_factory.cpython-39-x86_64-linux-gnu.so
[63/114] Copying Cython-generated headers to dpctl
[64/114] Linking CXX shared module dpctl/_sycl_platform.cpython-39-x86_64-linux-gnu.so
[65/114] Copying Cython-generated headers to dpctl
[66/114] Building CXX object dpctl/CMakeFiles/_sycl_event.dir/_sycl_event.cxx.o
[67/114] Linking CXX shared module dpctl/_sycl_event.cpython-39-x86_64-linux-gnu.so
[68/114] Copying Cython-generated headers to dpctl
[69/114] Generating CXX source dpctl/tensor/_flags.cxx
[70/114] Generating CXX source dpctl/tensor/_dlpack.cxx
[71/114] Generating CXX source dpctl/tensor/_usmarray.cxx
[72/114] Generating CXX source dpctl/utils/_compute_follows_data.cxx
[73/114] Building CXX object dpctl/CMakeFiles/_sycl_device.dir/_sycl_device.cxx.o
[74/114] Linking CXX shared module dpctl/_sycl_device.cpython-39-x86_64-linux-gnu.so
[75/114] Copying Cython-generated headers to dpctl
[76/114] Building CXX object dpctl/program/CMakeFiles/_program.dir/_program.cxx.o
[77/114] Building CXX object dpctl/CMakeFiles/_sycl_queue_manager.dir/_sycl_queue_manager.cxx.o
[78/114] Linking CXX shared module dpctl/program/_program.cpython-39-x86_64-linux-gnu.so
[79/114] Copying Cython-generated headers to dpctl
[80/114] Linking CXX shared module dpctl/_sycl_queue_manager.cpython-39-x86_64-linux-gnu.so
[81/114] Copying Cython-generated headers to dpctl
[82/114] Building CXX object dpctl/CMakeFiles/_sycl_context.dir/_sycl_context.cxx.o
[83/114] Linking CXX shared module dpctl/_sycl_context.cpython-39-x86_64-linux-gnu.so
[84/114] Copying Cython-generated headers to dpctl
[85/114] Building CXX object dpctl/tensor/CMakeFiles/_flags.dir/_flags.cxx.o
[86/114] Linking CXX shared module dpctl/tensor/_flags.cpython-39-x86_64-linux-gnu.so
[87/114] Copying Cython-generated headers to dpctl
[88/114] Building CXX object dpctl/tensor/CMakeFiles/_dlpack.dir/_dlpack.cxx.o
[89/114] Linking CXX shared module dpctl/tensor/_dlpack.cpython-39-x86_64-linux-gnu.so
[90/114] Copying Cython-generated headers to dpctl
[91/114] Building CXX object dpctl/utils/CMakeFiles/_compute_follows_data.dir/_compute_follows_data.cxx.o
[92/114] Building CXX object dpctl/memory/CMakeFiles/_memory.dir/_memory.cxx.o
[93/114] Linking CXX shared module dpctl/utils/_compute_follows_data.cpython-39-x86_64-linux-gnu.so
[94/114] Copying Cython-generated headers to dpctl
[95/114] Linking CXX shared module dpctl/memory/_memory.cpython-39-x86_64-linux-gnu.so
[96/114] Copying Cython-generated headers to dpctl
[97/114] Building CXX object dpctl/CMakeFiles/_sycl_queue.dir/_sycl_queue.cxx.o
[98/114] Linking CXX shared module dpctl/_sycl_queue.cpython-39-x86_64-linux-gnu.so
[99/114] Copying Cython-generated headers to dpctl
[100/114] Building CXX object dpctl/tensor/CMakeFiles/_usmarray.dir/_usmarray.cxx.o
[101/114] Linking CXX shared module dpctl/tensor/_usmarray.cpython-39-x86_64-linux-gnu.so
[102/114] Copying Cython-generated headers to dpctl
[103/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o
FAILED: dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o 
/opt/intel/oneapi/compiler/2022.2.1/linux/bin/icpx -D_tensor_impl_EXPORTS -I/home/jjerphan/dev/dpctl/dpctl/tensor/../include -I/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/include -I/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source -isystem /home/jjerphan/.local/share/miniconda3/envs/intel/include/python3.9 -isystem /home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-build/_deps/pybind11-src/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jjerphan/.local/share/miniconda3/envs/intel/include -fsycl  -O3 -Wall -Wextra -Winit-self -Wunused-function -Wuninitialized -Wmissing-declarations -fdiagnostics-color=auto -fstack-protector -fstack-protector-all -fpic -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fno-strict-overflow -fno-delete-null-pointer-checks -fsycl  -O3 -DNDEBUG -fPIC -fvisibility=hidden -ipo -std=c++17 -MD -MT dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o -MF dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o.d -o dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/simplify_iteration_space.cpp.o -c /home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source/simplify_iteration_space.cpp
In file included from /home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source/simplify_iteration_space.cpp:25:
In file included from /home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/source/simplify_iteration_space.hpp:26:
/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/include/utils/strided_iters.hpp:517:17: error: no member named 'make_tuple' in namespace 'std'
    return std::make_tuple(out_shape, out_strides, disp);
           ~~~~~^
/home/jjerphan/dev/dpctl/dpctl/tensor/libtensor/include/utils/strided_iters.hpp:540:17: error: no member named 'make_tuple' in namespace 'std'
    return std::make_tuple(out_shape, out_strides1, disp1, out_strides2, disp2);
           ~~~~~^
2 errors generated.
[104/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/device_support_queries.cpp.o
[105/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/tensor_py.cpp.o
[106/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/full_ctor.cpp.o
[107/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/eye_ctor.cpp.o
[108/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/copy_for_reshape.cpp.o
[109/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/triul_ctor.cpp.o
[110/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/linear_sequences.cpp.o
[111/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp.o
[112/114] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/copy_and_cast_usm_to_usm.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 640, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/skbuild/cmaker.py", line 672, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/skbuild/cmaker.py", line 703, in make_impl
    raise SKBuildError(

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /home/jjerphan/dev/dpctl
  Working directory:
    /home/jjerphan/dev/dpctl/_skbuild/linux-x86_64-3.9/cmake-build
Please check the install target is valid and see CMake's output for more information.
Traceback (most recent call last):
  File "/home/jjerphan/dev/dpctl/scripts/build_locally.py", line 167, in <module>
    run(
  File "/home/jjerphan/dev/dpctl/scripts/build_locally.py", line 63, in run
    subprocess.check_call(
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/jjerphan/.local/share/miniconda3/envs/intel/bin/python', 'setup.py', 'develop', '--build-type=Release', '--generator=Ninja', '--', '-DCMAKE_C_COMPILER:PATH=icx', '-DCMAKE_CXX_COMPILER:PATH=icpx', '-DDPCTL_ENABLE_L0_PROGRAM_CREATION=ON', '-DDPCTL_ENABLE_GLOG:BOOL=OFF']' returned non-zero exit status 1.
```

</details>

**Comment by jjerphan** [comment]
I just have opened https://github.com/IntelPython/dpctl/pull/1008 to try to address this issue.
