### ISSUE TITLE
RuntimeError: Null memory pointer returned

### ISSUE THREAD

**Issue by npolina4** [IntelPython/dpctl#1158]
Found on dpbench pairwise_distance run with size M.

It works on cpu.

```python
import dpctl.tensor as dpt
a = dpt.ones((32768, 32768), device='gpu')
dpt.asnumpy(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../dpctl/dpctl/tensor/_copy_utils.py", line 179, in asnumpy
    return _copy_to_numpy(usm_ary)
  File ".../dpctl/dpctl/tensor/_copy_utils.py", line 38, in _copy_to_numpy
    hh = dpm.MemoryUSMHost(nb, queue=ary.sycl_queue)
  File "dpctl/memory/_memory.pyx", line 730, in dpctl.memory._memory.MemoryUSMHost.__cinit__
  File "dpctl/memory/_memory.pyx", line 190, in dpctl.memory._memory._Memory._cinit_alloc
RuntimeError: Null memory pointer returned
```

**Comment by oleksandr-pavlyk** [comment]
Assuming `float64` data type, this matrix takes  8GB of memory. 

On my Iris Xe box I can only allocate 1GB of USM-host memory:

```
In [15]: dpm.MemoryUSMHost( 1024 * 1024 * 1024)
Out[15]: <SYCL(TM) USM-host allocation of 1073741824 bytes at 0x7fe983fff000>

In [16]: del _

In [17]: dpm.MemoryUSMHost( 1024 * 1024 * 1024 * 2)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [17], in <cell line: 1>()
----> 1 dpm.MemoryUSMHost( 1024 * 1024 * 1024 * 2)

File ~/repos/dpctl/dpctl/memory/_memory.pyx:730, in dpctl.memory._memory.MemoryUSMHost.__cinit__()

File ~/repos/dpctl/dpctl/memory/_memory.pyx:190, in dpctl.memory._memory._Memory._cinit_alloc()

RuntimeError: Null memory pointer returned
```

I can allocate more USM-device memory than that. Let me ask around about possible known limitation.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk At the least the error message needs to be improved. We should inform that an "OutOfMemory" error happened

**Comment by oleksandr-pavlyk** [comment]
How about `USMMemoryError` exception class?

**Comment by oleksandr-pavlyk** [comment]
After merge of #1161 the behavior is now:

```
In [1]: import dpctl

In [2]: import dpctl.memory as dpm

In [3]: dpm.MemoryUSMDevice( 1024 * 1024 * 1024 * 8)
---------------------------------------------------------------------------
USMAllocationError                        Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 dpm.MemoryUSMDevice( 1024 * 1024 * 1024 * 8)

File ~/repos/dpctl/dpctl/memory/_memory.pyx:783, in dpctl.memory._memory.MemoryUSMDevice.__cinit__()
    781           SyclQueue queue=None, int copy=False):
    782 if (isinstance(other, numbers.Integral)):
--> 783     self._cinit_alloc(alignment, <Py_ssize_t>other, b"device", queue)
    784 else:
    785     self._cinit_other(other)

File ~/repos/dpctl/dpctl/memory/_memory.pyx:201, in dpctl.memory._memory._Memory._cinit_alloc()
    199     self.queue = queue
    200 else:
--> 201     raise USMAllocationError(
    202         "USM allocation failed"
    203     )

USMAllocationError: USM allocation failed

In [4]: quit
```

Closing.
