### ISSUE TITLE
dpctl.tensor.abs() does not work on Iris Xe on Windows

### ISSUE THREAD

**Issue by npolina4** [IntelPython/dpctl#1279]
```python
import dpctl.tensor as dpt
a = dpt.ones(10, dtype='c8')
dpt.abs(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\npolina\devel\miniconda3\envs\dpnp_new\envs\dpnp1\lib\site-packages\dpctl\tensor\_elementwise_common.py", line 101, in __call__
    ht, _ = self.unary_fn_(x, out, sycl_queue=exec_q)
RuntimeError: Required aspect fp64 is not supported on the device
```

**Comment by oleksandr-pavlyk** [comment]
This problem is Windows specific, and can not be reproduced on Linux.
