### ISSUE TITLE
Development via `pip install -e .`

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#213]
`python -m pip install -e .` does not work.
```
Obtaining file:///localdisk/work/spokhode/dpctl
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /localdisk/work/spokhode/miniconda3/envs/dpctl-dev/bin/python /localdisk/work/spokhode/miniconda3/envs/dpctl-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3boiy7ix
       cwd: /localdisk/work/spokhode/dpctl
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/localdisk/work/spokhode/miniconda3/envs/dpctl-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/localdisk/work/spokhode/miniconda3/envs/dpctl-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/localdisk/work/spokhode/miniconda3/envs/dpctl-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/localdisk/tmp/pip-build-env-m7q94n69/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/localdisk/tmp/pip-build-env-m7q94n69/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/localdisk/tmp/pip-build-env-m7q94n69/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/localdisk/tmp/pip-build-env-m7q94n69/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 33, in <module>
      from Cython.Build import cythonize
  ModuleNotFoundError: No module named 'Cython'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /localdisk/work/spokhode/miniconda3/envs/dpctl-dev/bin/python /localdisk/work/spokhode/miniconda3/envs/dpctl-dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3boiy7ix Check the logs for full command output.
```

**Comment by PokhodenkoSA** [comment]
CC @Vyacheslav-Smirnov

**Comment by Vyacheslav-Smirnov** [comment]
I think there is need to add more details:
 - What Python is used
 - What system is used
 - What environment is used
 - What version of dpctl is used
 - What type of environment is used (conda, pure pip, no virtual env)
 - Versions on packages in environment

**Comment by PokhodenkoSA** [comment]
Python 3.7
Ubuntu 20.04
conda list:
```
(dpctl-dev) spokhode@ansatnuc06:/localdisk/work/spokhode/dpctl$ conda list
# packages in environment at /localdisk/work/spokhode/miniconda3/envs/dpctl-dev:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h88c068d_5    http://10.241.130.213:8081
certifi                   2020.11.8                py37_0    http://10.241.130.213:8081
intelpython               2021.1.1                      1    http://10.241.130.213:8081
libffi                    3.3                          13    http://10.241.130.213:8081
libgcc-ng                 9.3.0              hdf63c60_101    http://10.241.130.213:8081
libstdcxx-ng              9.3.0              hdf63c60_101    http://10.241.130.213:8081
openssl                   1.1.1h               h14c3975_0    http://10.241.130.213:8081
pip                       20.2.4                   py37_0    http://10.241.130.213:8081
python                    3.7.9                h9706ba9_1    http://10.241.130.213:8081
setuptools                50.3.2                   py37_0    http://10.241.130.213:8081
sqlite                    3.34.0               h88c068d_0    http://10.241.130.213:8081
tcl                       8.6.9               h14c3975_27    http://10.241.130.213:8081
tk                        8.6.9                h842114c_8    http://10.241.130.213:8081
wheel                     0.35.1                   py37_1    http://10.241.130.213:8081
xz                        5.2.5                hc829aee_2    http://10.241.130.213:8081
zlib                      1.2.11.1             hb8a9d29_3    http://10.241.130.213:8081
```
dpctl from master branch.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk is this related to dpctl not providing a requirements.txt?

**Comment by PokhodenkoSA** [comment]
> is this related to dpctl not providing a requirements.txt?

No.

**Comment by Vyacheslav-Smirnov** [comment]
Maybe just need to add cython in install_requires?
