### ISSUE TITLE
Problem in integration TeamCity and coverage

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#373]
In CI you can see
```bash
  Coverage statistics reporting failed
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.7/site-packages/teamcity_messages-1.25-py3.7.egg/teamcity/pytest_plugin.py", line 371, in pytest_terminal_summary
      self._report_coverage()
    File "$PREFIX/lib/python3.7/site-packages/teamcity_messages-1.25-py3.7.egg/teamcity/pytest_plugin.py", line 378, in _report_coverage
      from coverage.report import Reporter
  ImportError: cannot import name 'Reporter' from 'coverage.report' ($PREFIX/lib/python3.7/site-packages/coverage/report.py)
```
It should be fixed by [SAT-3964](https://jira.devtools.intel.com/browse/SAT-3964).

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/dpctl/issues/369#issuecomment-814112417_

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I am closing the issue as doubt it will be fixed any time soon. We anyway have coverage generated via github actions.
