### ISSUE TITLE
dpctl.tensor.reshape raises ValueError with empty list as input

### ISSUE THREAD

**Issue by LukichevaPolina** [IntelPython/dpctl#729]
Reproduces:
```
import dpctl.tensor as dpt

a = dpt.asarray([])
dpt.reshape(a, (0,))
```
Output:
```
Traceback (most recent call last):
  File "/localdisk/work/plukiche/dpnp_fork/dpctl_empty_reshape_repro.py", line 4, in <module>
    dpt.reshape(a, (0,))
  File "/localdisk/work/plukiche/miniconda/miniconda3/envs/dpnptc4_internal/lib/python3.8/site-packages/dpctl/tensor/_reshape.py", line 107, in reshape
    newsts = reshaped_strides(X.shape, X.strides, newshape, order=order)
  File "/localdisk/work/plukiche/miniconda/miniconda3/envs/dpnptc4_internal/lib/python3.8/site-packages/dpctl/tensor/_reshape.py", line 50, in reshaped_strides
    for flat_index in [
  File "/localdisk/work/plukiche/miniconda/miniconda3/envs/dpnptc4_internal/lib/python3.8/site-packages/dpctl/tensor/_reshape.py", line 51, in <listcomp>
    np.ravel_multi_index(unitvec, new_sh, order=order)
  File "<__array_function__ internals>", line 5, in ravel_multi_index
ValueError: cannot unravel if shape has zero entries (is empty).
```
dpctl version is `0.12.0dev1+104.gccd21b68`

**Comment by LukichevaPolina** [comment]
@oleksandr-pavlyk, Could you please look at this problem?

**Comment by densmirn** [comment]
@oleksandr-pavlyk, could you please either leave a comment or prepare a fix on this issue? The issue is blocking DPNP testing in external CI.

**Comment by oleksandr-pavlyk** [comment]
The immediate error is caused by attempting to use `np.ravel_multi_index` for shape with zero elements. That case should be handled separately.
